# Tugas 5 Praktikum Metode Numerik

**Faza Muthmainnah - NPM 2006523672 - Kelas Metnum (B)**

NPM Genap: Scaled Partial Pivoting

In [9]:
import numpy as np

npm = np.array(eval(input('Masukkan 5 digit terakhir NPM kamu: ')),dtype=float) #input matriks dengan bilangan npm
FZ = np.random.randint(-100,100, size = (3,5)) #memilih acak bilangan pada matriks ukuran baris 3, kolom 5                                 
FZ1 = np.vstack([FZ,npm]) #memasukkan matriks npm ke matriks FZ                

#mendefinisikan fungsi scaled partial pivoting
def ScaledPartialPivoting(matrix):                                             
    n = np.shape(matrix)[0] #membuat fungsi n untuk menghitung jumlah persamaan pada matriks                                                
    s = np.array([max(abs(matrix[i,:n])) for i in range(n)]) #membuat fungsi s untuk menentukan skalar pada setiap kolom matriks
    if 0 in s:
        return "SPL tidak memiliki solusi unik" 
    for i in range(n-1):
        below_pivot = abs(matrix[i:,i])/s[i:]
        pivot_row = np.argmax(below_pivot)
        if matrix[i,pivot_row+i] == 0:
            return "SPL tidak memiliki solusi unik"
        else:
            matrix[[pivot_row+i,i]] = matrix[[i,pivot_row+i]]
            s[pivot_row+i],s[i] = s[i],s[pivot_row+i]
            
        #eliminasi gauss
        for j in range(i+1,n): 
            m = matrix[j,i]/matrix[i,i] #membuat fungsi m untuk melakukan operasi baris elementer
            matrix[j] = matrix[j]-m*matrix[i]
        print(matrix)
        print(' ')
    return matrix

#mendefinisikan fungsi back substitution/substitusi balik
def BackSub(matrix):                                                          
    n = np.shape(matrix)[0] #jumlah persamaan pada SPL (jumlah baris pada matriks)                                                  
    sol = np.zeros(n)  #membuat array 0 berjumlah n                                             
    sol[n-1]= matrix[n-1,n]/matrix[n-1,n-1] #menghitung xn                                 
    for i in range(n-2,-1,-1):                                               
        for j in range(i+1,n):
            matrix[i,n]-=matrix[i,j]*sol[j]
        sol[i] = matrix[i,n]/matrix[i,i]
    return sol

print("Augmented matriks yang terbentuk dari SPL :")                        
print(M1) #mencetak hasil augmented matriks yang terbentuk
print('==========================================================================================')
solution = ScaledPartialPivoting(A1) 
print(f"Solusi SPL : \n {BackSub(solution)}") #mencetak hasil/solusi SPL nya

Masukkan 5 digit terakhir NPM kamu: [2,3,6,7,2]
Augmented matriks yang terbentuk dari SPL :
[[ -6.  99.  25.  13. -63.]
 [ 66.  60. -30.  95.  18.]
 [-69.  61. -93.  19.  52.]
 [  2.   3.   6.   7.   2.]]
[[  68.          -37.          -24.           45.          -23.61213149]
 [   0.           54.30882353   80.47058824  -27.13235294  -78.45375565]
 [   0.            0.          100.58326564 -131.39073924   52.70418831]
 [   0.            0.            0.            8.56573358    1.49537224]]
 
[[  68.          -37.          -24.           45.          -23.61213149]
 [   0.           54.30882353   80.47058824  -27.13235294  -78.45375565]
 [   0.            0.          100.58326564 -131.39073924   52.70418831]
 [   0.            0.            0.            8.56573358    1.49537224]]
 
[[  68.          -37.          -24.           45.          -23.61213149]
 [   0.           54.30882353   80.47058824  -27.13235294  -78.45375565]
 [   0.            0.          100.58326564 -131.39073924  